ManageAssets/Controllers/Sys_GroupPermissionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ManageAssets.Models;

namespace ManageAssets.Controllers
{
    public class Sys_GroupPermissionController : BaseController
    {
        AssetsManagerEntities db = new AssetsManagerEntities();
        // GET: Sys_GroupPermission
        public ActionResult Index()
        {
            List<Sys_GroupPermision> lstAccountPermission = db.Sys_GroupPermision.ToList();
            return View(lstAccountPermission);
        }

        // GET: Sys_GroupPermission/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Sys_GroupPermission/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sys_GroupPermission/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    
        //GET: View had Permission in Sys_GroupPermission
        public ActionResult Partial_ViewPermission(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<Sys_GroupPermisionDetail> lstGroupPermission = db.Sys_GroupPermisionDetail.Where(p => p.GroupID == id).OrderBy(p=>p.Action_ID).ToList();

            return PartialView(lstGroupPermission);
        }

        //GET: Get All Sys_Action
        public ActionResult Partial_ViewAllAction(string GroupId)
        {
            ViewBag.GroupId = GroupId;
            List<Sys_Action> lstAction = db.Sys_Action.Where(a => !db.Sys_GroupPermisionDetail.Select(m => m.Action_ID).Contains(a.Action_ID)).OrderBy(p=>p.Action_ID).ToList();
            return PartialView(lstAction);
        }

        //GET: Add Action to GroupPermission
        public ActionResult AddAction_to_GroupPermission(string id, string GroupID)
        {
            Sys_GroupPermisionDetail groupPermission = new Sys_GroupPermisionDetail();
            groupPermission.GroupID = GroupID;
            groupPermission.Action_ID = id;
            db.Sys_GroupPermisionDetail.Add(groupPermission);
            db.SaveChanges();

            // Update Session Authorize
            Sys_Account user = (Sys_Account)Session["UserAccount"]; 
            List<string> lst = (from a in db.Sys_Account
                                join b in db.Sys_AccountPermission on a.Username equals b.Username
                                join c in db.Sys_GroupPermisionDetail on b.GroupID equals c.GroupID
                                where a.Username == user.Username
                                select (c.Action_ID)).ToList();
            Session["UserAuthorize"] = lst;

            return RedirectToAction("Edit", new { id = GroupID });
        }

        //GET: Remove Action GroupPermission
        public ActionResult Remove_GroupPermission(int id, string groupId)
        {
            Sys_GroupPermisionDetail detail = db.Sys_GroupPermisionDetail.Find(id);
            db.Sys_GroupPermisionDetail.Remove(detail);
            db.SaveChanges();

            // Update Session Authorize
            Sys_Account user = (Sys_Account)Session["UserAccount"];
            List<string> lst = (from a in db.Sys_Account
                                join b in db.Sys_AccountPermission on a.Username equals b.Username
                                join c in db.Sys_GroupPermisionDetail on b.GroupID equals c.GroupID
                                where a.Username == user.Username
                                select (c.Action_ID)).ToList();
            Session["UserAuthorize"] = lst;

            return RedirectToAction("Edit", new { id = groupId });
        }
        // GET: Sys_GroupPermission/Edit/5
        public ActionResult Edit(string id)
        {
            ViewBag.GroupId = id;
            return View();
        }

        // POST: Sys_GroupPermission/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Sys_GroupPermission/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Sys_GroupPermission/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ManageAssets/Views/Sys_GroupPermission/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Reports_LayoutPage.cshtml";
}


<div class="row">
    <div class="col-md-6 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>My Permission</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="#">Settings 1</a>
                            </li>
                            <li>
                                <a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                @{ Html.RenderAction("Partial_ViewPermission", "Sys_GroupPermission");}
            </div>
        </div>
    </div>
    <div class="col-md-6 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>All action in system</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="#">Settings 1</a>
                            </li>
                            <li>
                                <a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                

                <div class="x_content1">
                    @{ Html.RenderAction("Partial_ViewAllAction", "Sys_GroupPermission", new { GroupId = ViewBag.GroupId });}
                </div>
            </div>
        </div>
    </div>
</div>

ManageAssets/Views/Sys_GroupPermission/Index.cshtml
@model IEnumerable<ManageAssets.Models.Sys_GroupPermision>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Reports_LayoutPage.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.GroupID)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.GroupID)
        </td>
        <td>
            @Html.ActionLink("Edit Permission", "Edit", new { id=item.GroupID })
            @*| @Html.ActionLink("Details", "Details", new { id=item.GroupID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.GroupID })*@
        </td>
    </tr>
}

</table>

ManageAssets/Views/Sys_GroupPermission/Partial_ViewAllAction.cshtml
@model IEnumerable<ManageAssets.Models.Sys_Action>

@ViewBag.GroupId
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Action_ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Action_Name_Vi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Action_Name_En)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Action_Name_Cn)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Action_ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Action_Name_Vi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Action_Name_En)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Action_Name_Cn)
            </td>
            <td>@Html.ActionLink("Add","AddAction_to_GroupPermission","Sys_GroupPermission", new { id = item.Action_ID, GroupID = ViewBag.GroupID},null)</td>
            @*<td><a href="#" class="click" onclick="loadPage()" >Add</a></td>*@
        </tr>
    }

</table>


@*<p id="timer"></p>*@

@*<script>
    var $timer = $('.x_content1');
    function loadPage() {
        var options = {
            url: '/Sys_GroupPermission/Partial_ViewAllAction',
            data: { id : 'Payments-ExportPdf', GroupID : 'Administrator' },
            success: function (time) {
                $timer.html('').html(time);
            }
        };
        $.ajax(options);
        console.log(options);
    };
</script>*@

@*
    <script type="text/javascript">
                    ///Sys_GroupPermission/AddAction_to_GroupPermission/Payments-ExportPdf?GroupID=Administrator
                    function loadPage() {
                        //var url = "@(Html.Raw(Url.Action("AddAction_to_GroupPermission", "Sys_GroupPermission")))";
                        var $id = $('.id');
                        var $GroupId = $('.GroupId');

                        $.ajax({
                            //url: "/Sys_GroupPermission/Partial_ViewAllAction/Payments-ExportPdf?GroupID=Administrator",
                            url: "@Url.Action("Partial_ViewAllAction", "Sys_GroupPermission")",
                            type: "POST",
                            //data: $("form").serialize(), //if you need to post Model data, use this
                            data: { $id, $GroupId },
                            success: function (result) {
                                $("#x_content1").html(result);
                                //$("#x_content1").load();
                                alert("1");
                            }
                        });
                    }
    </script>
*@

ManageAssets/Views/Sys_GroupPermission/Partial_ViewPermission.cshtml
@model IEnumerable<ManageAssets.Models.Sys_GroupPermisionDetail>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Action_ID)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Action_Name_Vi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Action_Name_En)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Action_Name_Cn)
        </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Action_ID)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Sys_Action.Action_Name_Vi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sys_Action.Action_Name_En)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sys_Action.Action_Name_Cn)
            </td>*@
            <td>
                @Html.ActionLink("Remove", "Remove_GroupPermission", "Sys_GroupPermission",new { id = item.GPD_Id, groupId = item.GroupID}, null)
            </td>
        </tr>
    }

</table>