ManageAssets/Controllers/Sys_ControllerController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ManageAssets.Helper;
using ManageAssets.Models;

namespace ManageAssets.Controllers
{
    public class Sys_ControllerController : Controller
    {
        AssetsManagerEntities db = new AssetsManagerEntities();
        // Update Controller
        public ActionResult UpdateController()
        {
            SaveReflectionController save = new SaveReflectionController();
            save.SaveReflection();
            return RedirectToAction("index");
        }
        // NotificationAuthozide
        public ActionResult NotificationAuthozide()
        {
            return View();
        }
        // GET: Sys_Controller
        public ActionResult Index()
        {
            List<Sys_Controller> lstController = db.Sys_Controller.ToList();
            return View(lstController);
        }

        // GET: Sys_Controller/Details/5
        public ActionResult Details(string id)
        {
            return RedirectToAction("Index","Sys_Action",new { id = id});
        }

        // GET: Sys_Controller/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sys_Controller/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Sys_Controller/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sys_Controller lst = db.Sys_Controller.Find(id);
            if (lst == null)
            {
                return HttpNotFound();
            }
            return View(lst);
        }

        // POST: Sys_Controller/Edit/5
        [HttpPost]
        public ActionResult Edit(Sys_Controller ctr)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ctr).State = EntityState.Modified;

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: Sys_Controller/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Sys_Controller/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ManageAssets/Views/Sys_Controller/Edit.cshtml
@model ManageAssets.Models.Sys_Controller
@using ManageAssets.Resources
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Reports_LayoutPage.cshtml";
}

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Form edit</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="#">Settings 1</a>
                            </li>
                            <li>
                                <a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                @using (Html.BeginForm("Edit", "Sys_Controller", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal form-label-left" }))
                {
                    @Html.AntiForgeryToken()
                    <p>
                        For alternative validation library <code>parsleyJS</code> check out in the <a href="form.html">form page</a>
                    </p>
                    <span class="section">Edit Controller</span>
                    <div>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Controller_ID)
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                @Html.DisplayName(Global.Controller_ID)
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(model => model.Controller_ID, new { @class = "col-md-7 col-xs-12 form-control ", @readonly = "True" })
                            </div>
                        </div>

                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                @Html.DisplayName(Global.Controller_Name_Vi)
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.EditorFor(model => model.Controller_Name_Vi, new { htmlAttributes = new { @class = "datepicker col-md-7 col-xs-12 form-control" } })
                                @Html.ValidationMessageFor(model => model.Controller_Name_Vi, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                @Html.DisplayName(Global.Controller_Name_En)
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.EditorFor(model => model.Controller_Name_En, new { htmlAttributes = new { @class = "datepicker col-md-7 col-xs-12 form-control" } })
                                @Html.ValidationMessageFor(model => model.Controller_Name_En, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                @Html.DisplayName(Global.Controller_Name_Cn)
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.EditorFor(model => model.Controller_Name_Cn, new { htmlAttributes = new { @class = "datepicker col-md-7 col-xs-12 form-control" } })
                                @Html.ValidationMessageFor(model => model.Controller_Name_Cn, "", new { @class = "text-danger" })
                            </div>
                        </div>


                        <div class="item form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-default" />
                            </div>
                        </div>
                        <p>
                            @Html.ActionLink("Back to List", "Index")
                        </p>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

ManageAssets/Views/Sys_Controller/Index.cshtml
@model IEnumerable<ManageAssets.Models.Sys_Controller>
@using ManageAssets.Resources


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Reports_LayoutPage.cshtml";
}


<div class="x_panel">
    <div class="x_title">
        <h2>Controller Manager</h2>
        <br />
        <div class="clearfix"></div>
        @Html.ActionLink("Update Controller", "UpdateController", "Sys_Controller", new { @class = "btn btn-info" })
        <ul class="nav navbar-right panel_toolbox">
            <li>
                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                    <li>
                        <a href="#">Settings 1</a>
                    </li>
                    <li>
                        <a href="#">Settings 2</a>
                    </li>
                </ul>
            </li>
            <li>
                <a class="close-link"><i class="fa fa-close"></i></a>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">
        <p class="text-muted font-13 m-b-30">
            Responsive is an extension for DataTables that resolves that problem by optimising the table's layout for different screen sizes through the dynamic insertion and removal of columns from the table.
        </p>

        <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayName(Global.Controller_ID)
                    </th>
                    <th>
                        @Html.DisplayName(Global.Controller_Name_Vi)
                    </th>
                    <th>
                        @Html.DisplayName(Global.Controller_Name_En)
                    </th>
                    <th>
                        @Html.DisplayName(Global.Controller_Name_Cn)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Controller_ID, new { @id = "username" })
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Controller_Name_Vi)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Controller_Name_En)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Controller_Name_Cn)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Controller_ID }) |
                            @Html.ActionLink("Details", "Details", new { id = item.Controller_ID })
                            @*|@Html.ActionLink("Delete", "Delete", new { id = item.Controller_ID })*@
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

ManageAssets/Views/Sys_Controller/NotificationAuthozide.cshtml
@{
    ViewBag.Title = "NotificationAuthozide";
    Layout = null;
}
@*<meta http-equiv="Refresh" content="3; url=http://localhost:54886/">*@
<h1>
    Bạn không có quyền truy cập, sau 3s chuyển về trang đăng nhập
</h1>
<h2>NotificationAuthozide, after 3s redirect to login page</h2>

@Html.ActionLink("Back Home","Index","Home") | @Html.ActionLink("Login","Index","Sys_Login")